spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ees?useSSL=false&serverTimezone=Asia/Tokyo&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
    locations: classpath:db/migration
